### ISSUE TITLE
Remove dependency on `distutils`

### ISSUE THREAD

**Issue by yguclu** [pyccel/psydac#406]
In order to support the most recent Python versions, we should remove any dependency on the `distutils` module, as this is not part of `python 3.12`. To this end we must:

- [x] Remove the `distutils` import from our [setup.py](https://github.com/pyccel/psydac/blob/devel/setup.py)
- [x] Make sure that SymPDE uses `sympy >= 1.12` (hence we must fix the SymPDE issue [#106](https://github.com/pyccel/sympde/issues/106))
- [x] Either drop the Igakit dependency, or update Igakit so that it does not use `distutils` to build the Fortran extension modules (see issue #53)

**Comment by kvrigor** [comment]
Some updates:

* Remove the distutils import from our [setup.py](https://github.com/pyccel/psydac/blob/devel/setup.py) 
  - Addressed in #407
* Either drop the Igakit dependency, or update Igakit so that it does not use distutils to build the Fortran extension modules
  - Migration to Meson in progress:  [`pyccel/igakit#meson-build`](https://github.com/pyccel/igakit/tree/meson-build)

**Comment by kvrigor** [comment]
With [igakit Py3.12](https://github.com/dalcinl/igakit/pull/5) already supported, we can close this issue.
