### ISSUE TITLE
Deprecation Warning for np.reshape

### ISSUE THREAD

**Issue by FrederikSchnack** [pyccel/psydac#432]
When reinstalling psydac and running the tests, I got this warning
> DeprecationWarning: `newshape` keyword argument is deprecated, use `shape=...` or pass shape positionally instead. (deprecated in NumPy 2.1)`

in the `np.reshape` function. Since this is essentially removing three letters, I figured I could fix this while waiting for the other tests to finish. (I also added `shape=` in the other occurrences for consistency) 
See #433.

**Comment by FrederikSchnack** [comment]
Nvm, since NumPy >= 2.1 is not supporting Python 3.9, this will make the tests fail. So maybe it's not a good idea to change that now.

**Comment by campospinto** [comment]
Dropping Python 3.9 seems a bit premature, see https://devguide.python.org/versions/

**Comment by yguclu** [comment]
Does the `reshape` function accept the `shape` argument prior to NumPy 2.1?

**Comment by FrederikSchnack** [comment]
No, this was only introduced with the (stable) NumPy 2.1 version. As proposed in #433 we could pass the shape argument positionally to avoid the warning and be compatible with all versions.

**Comment by yguclu** [comment]
If I understand correctly the [documentation](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html#numpy-reshape) of the latest version, the new `shape` parameter is `positional-only` (see [PEP 570](https://peps.python.org/pep-0570/)) because it follows the `/` character in the function signature:
```python
numpy.reshape(a, /, shape=None, *, newshape=None, order='C', copy=None)
```
Hence your solution is the only one possible.
